### ISSUE TITLE
Add warped triangles pwetty pweaze

### ISSUE THREAD

**Issue by Decoder0007** [CoCuCoH41k/G2GD#2]
So like triangles but in any shape you want

**Comment by CoCuCoH41k** [comment]
I really want, and in gd triangles can be created by vertex gradient trigger. But here's little issue: gradient trigger always on top of the layer, and we cant change z order of it. So, heres also a hard ways, ill try soon.

**Comment by Decoder0007** [comment]
You would need to use the right angled slope object and then set its warp
and scale values To make it look like any triangle you Want
